server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://34.69.173.81:3306/ReimbursementApp
  # allows capitalization for your tables
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl